# AI-Based Retail Inventory Intelligence System

## Notebook 2 : Deployment & Prediction Pipeline

### Objective

This notebook demonstrates how the trained machine learning model is integrated into a real-world Retail Inventory Intelligence System.

The notebook includes:

- Loading the trained model
- Loading label encoders
- Loading feature columns
- Creating a product database
- Building the prediction pipeline
- Inventory intelligence engine
- Testing the complete system

## Step 1 : Mount Google Drive

In [1]:
import pandas as pd

df = pd.read_csv(
    "../Dataset/retail_inventory_15000.csv"
)

## Step 2 : Import Required Libraries

In [2]:
import pandas as pd
import numpy as np
import joblib

## Step 3 : Load Saved AI Model

In [3]:
import joblib

# Load trained model
model = joblib.load(
    "../Models/final_inventory_model.pkl"
)

# Load encoders
encoders = joblib.load(
    "../Models/label_encoders.pkl"
)

# Load feature order
feature_columns = joblib.load(
    "../Models/feature_columns.pkl"
)

print("AI System Loaded Successfully!")

AI System Loaded Successfully!

In [4]:
print(type(model))

print()

print(encoders.keys())

print()

print(feature_columns)

<class 'sklearn.ensemble._forest.RandomForestRegressor'>

dict_keys(['Store ID', 'Product ID', 'Category', 'Region', 'Weather Condition', 'Seasonality'])

['Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion', 'Competitor Pricing', 'Seasonality', 'Month', 'Day']

In [5]:
## Step 5 : Load Product Database

In [6]:
import pandas as pd

# Load the dataset
dataset_path = "../Dataset/retail_inventory_15000.csv"

products_df = pd.read_csv(
    dataset_path,
    dayfirst=True
)

print("Product database loaded successfully!")
print("Shape:", products_df.shape)

products_df.head()

Product database loaded successfully!
Shape: (15000, 15)

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,25-04-2022,S005,P0020,Furniture,South,288,134,130,129.21,40.17,5,Sunny,0,43.66,Spring
1,06-03-2022,S004,P0016,Groceries,West,469,465,113,455.31,19.63,0,Sunny,0,22.30,Summer
2,12-05-2022,S004,P0008,Toys,South,386,321,105,313.55,29.24,15,Cloudy,0,33.03,Summer
3,09-01-2022,S004,P0003,Toys,East,306,58,54,64.75,89.88,10,Snowy,0,94.46,Spring
4,01-03-2022,S004,P0011,Toys,East,458,319,57,337.32,92.74,5,Sunny,1,88.03,Winter

## Step 6 : Create Product Master Database

In [7]:
# Select only required product information

product_master = products_df[
    [
        "Store ID",
        "Product ID",
        "Category",
        "Region",
        "Price",
        "Competitor Pricing",
        "Seasonality"
    ]
]

# Remove duplicate products

product_master = product_master.drop_duplicates()

print("Product Master Database Created!")

print("\nShape :", product_master.shape)

product_master.head()

Product Master Database Created!

Shape : (15000, 7)

  Store ID Product ID   Category Region  Price  Competitor Pricing Seasonality
0     S005      P0020  Furniture  South  40.17               43.66      Spring
1     S004      P0016  Groceries   West  19.63               22.30      Summer
2     S004      P0008       Toys  South  29.24               33.03      Summer
3     S004      P0003       Toys   East  89.88               94.46      Spring
4     S004      P0011       Toys   East  92.74               88.03      Winter

## Step 7 : Create Latest Product Master Database

In [8]:
# Step 7 : Create Latest Product Database

# Find the latest date in the dataset
latest_date = products_df["Date"].max()

print("Latest Date :", latest_date)

Latest Date : 31-03-2022

In [9]:
# Keep only the latest records

latest_products = products_df[
    products_df["Date"] == latest_date
].copy()

print("Latest Product Database Created!")
print("Shape :", latest_products.shape)

latest_products.head(10)

Latest Product Database Created!
Shape : (100, 15)

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
23,31-03-2022,S005,P0012,Clothing,West,440,414,160,417.46,49.78,20,Snowy,1,50.86,Autumn
191,31-03-2022,S002,P0018,Electronics,East,338,315,135,330.29,83.94,0,Sunny,1,79.93,Autumn
294,31-03-2022,S001,P0001,Clothing,South,358,85,151,91.85,63.02,0,Sunny,0,61.79,Autumn
396,31-03-2022,S005,P0014,Clothing,West,311,119,155,113.85,75.74,5,Sunny,1,78.34,Winter
430,31-03-2022,S002,P0015,Furniture,East,408,238,145,256.95,72.25,5,Sunny,1,70.80,Winter
512,31-03-2022,S002,P0010,Electronics,East,144,54,61,63.39,44.58,0,Cloudy,0,47.41,Summer
639,31-03-2022,S003,P0018,Clothing,South,218,210,116,216.14,66.51,5,Rainy,0,70.26,Winter
1169,31-03-2022,S001,P0011,Clothing,North,360,259,120,253.54,33.23,20,Cloudy,1,31.05,Winter
1203,31-03-2022,S004,P0009,Clothing,West,387,293,58,310.98,21.03,20,Rainy,0,24.29,Winter
1244,31-03-2022,S003,P0008,Clothing,North,303,106,154,99.58,49.88,20,Rainy,0,47.16,Spring

Step 8:Create the function

In [10]:
# Step 8 : Search Product

def get_product_details(product_id):

    product = latest_products[
        latest_products["Product ID"] == product_id
    ]

    if product.empty:
        print("❌ Product not found!")
        return None

    return product

In [11]:
get_product_details("P0005")

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
4973,31-03-2022,S003,P0005,Toys,North,457,349,177,357.52,50.87,5,Rainy,1,50.16,Autumn
6788,31-03-2022,S001,P0005,Clothing,North,414,103,144,117.24,85.09,15,Sunny,1,82.32,Spring
11976,31-03-2022,S004,P0005,Clothing,West,416,288,46,295.22,44.63,5,Snowy,1,39.86,Winter
12852,31-03-2022,S005,P0005,Groceries,North,254,202,68,218.90,30.52,20,Cloudy,1,27.40,Summer
14219,31-03-2022,S002,P0005,Electronics,West,440,348,27,358.16,61.64,0,Cloudy,0,59.79,Spring

step 9.1:Prepare Product for Prediction

In [14]:
# Step 9.1 : Prepare Product for Prediction

def prepare_input(product_row):

    input_data = product_row.copy()

    # Convert Date
    input_data["Date"] = pd.to_datetime(
        input_data["Date"],
        format="%d-%m-%Y"
    )

    # Extract Year, Month and Day
    input_data["Year"] = input_data["Date"].dt.year
    input_data["Month"] = input_data["Date"].dt.month
    input_data["Day"] = input_data["Date"].dt.day

    # Remove columns not used by the model
    input_data = input_data.drop(
        columns=[
            "Date",
            "Units Sold",
            "Units Ordered",
            "Demand Forecast",
            "Year"
        ],
        errors="ignore"
    )

    return input_data

In [15]:
product = get_product_details("P0005")

prepared = prepare_input(product)

prepared.head()

,Store ID,Product ID,Category,Region,Inventory Level,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,Month,Day
4973,S003,P0005,Toys,North,457,50.87,5,Rainy,1,50.16,Autumn,3,31
6788,S001,P0005,Clothing,North,414,85.09,15,Sunny,1,82.32,Spring,3,31
11976,S004,P0005,Clothing,West,416,44.63,5,Snowy,1,39.86,Winter,3,31
12852,S005,P0005,Groceries,North,254,30.52,20,Cloudy,1,27.40,Summer,3,31
14219,S002,P0005,Electronics,West,440,61.64,0,Cloudy,0,59.79,Spring,3,31

Step 9.2: Encode the Categorical Columns

In [16]:
# Step 9.2 : Encode categorical columns

def encode_input(input_data):

    encoded = input_data.copy()

    for col in encoders.keys():

        encoded[col] = encoders[col].transform(encoded[col])

    return encoded

In [17]:
encoded = encode_input(prepared)

encoded.head()

,Store ID,Product ID,Category,Region,Inventory Level,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,Month,Day
4973,2,4,4,1,457,50.87,5,1,1,50.16,0,3,31
6788,0,4,0,1,414,85.09,15,3,1,82.32,1,3,31
11976,3,4,0,3,416,44.63,5,2,1,39.86,3,3,31
12852,4,4,3,1,254,30.52,20,0,1,27.40,2,3,31
14219,1,4,1,3,440,61.64,0,0,0,59.79,1,3,31

In [18]:
encoded = encode_input(prepared)

encoded.head()

,Store ID,Product ID,Category,Region,Inventory Level,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,Month,Day
4973,2,4,4,1,457,50.87,5,1,1,50.16,0,3,31
6788,0,4,0,1,414,85.09,15,3,1,82.32,1,3,31
11976,3,4,0,3,416,44.63,5,2,1,39.86,3,3,31
12852,4,4,3,1,254,30.52,20,0,1,27.40,2,3,31
14219,1,4,1,3,440,61.64,0,0,0,59.79,1,3,31

In [19]:
# Arrange columns exactly as used during training
encoded = encoded[feature_columns]

print(encoded.columns.tolist())

['Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion', 'Competitor Pricing', 'Seasonality', 'Month', 'Day']

In [20]:
print(encoded.columns.tolist())

['Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion', 'Competitor Pricing', 'Seasonality', 'Month', 'Day']

In [21]:
print(feature_columns)

['Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion', 'Competitor Pricing', 'Seasonality', 'Month', 'Day']

In [22]:
prediction = model.predict(encoded)

print("Predicted Units Sold:")
print(prediction)

Predicted Units Sold:
[222.51330168 189.53769982 232.63134569 148.68189134 238.26231532]

In [23]:
result = prepared.copy()

result["Predicted Units Sold"] = prediction

result

,Store ID,Product ID,Category,Region,Inventory Level,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,Month,Day,Predicted Units Sold
4973,S003,P0005,Toys,North,457,50.87,5,Rainy,1,50.16,Autumn,3,31,222.513302
6788,S001,P0005,Clothing,North,414,85.09,15,Sunny,1,82.32,Spring,3,31,189.537700
11976,S004,P0005,Clothing,West,416,44.63,5,Snowy,1,39.86,Winter,3,31,232.631346
12852,S005,P0005,Groceries,North,254,30.52,20,Cloudy,1,27.40,Summer,3,31,148.681891
14219,S002,P0005,Electronics,West,440,61.64,0,Cloudy,0,59.79,Spring,3,31,238.262315

In [24]:
result[["Product ID", "Predicted Units Sold"]]

      Product ID  Predicted Units Sold
4973       P0005            222.513302
6788       P0005            189.537700
11976      P0005            232.631346
12852      P0005            148.681891
14219      P0005            238.262315